DROP SCHEMA IF EXISTS PARSER;

CREATE SCHEMA IF NOT EXISTS `PARSER`;

CREATE TABLE IF NOT EXISTS `PARSER`.`LOG_ENTRIES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `REQUEST_DATE` TIMESTAMP(3) NOT NULL,
  `IP_ADDRESS` INT UNSIGNED NOT NULL,
  `REQUEST_METHOD` VARCHAR(20) NOT NULL,
  `STATUS` SMALLINT NOT NULL,
  `USER_AGENT` VARCHAR(255) NOT NULL,
  UNIQUE (`REQUEST_DATE`, `IP_ADDRESS`),
  PRIMARY KEY (`ID`),
  INDEX `IP_ADDRESS` (`IP_ADDRESS` ASC)
);

CREATE TABLE IF NOT EXISTS `PARSER`.`BLOCKED_IPS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IP_ADDRESS` INT UNSIGNED NOT NULL,
  `NUM_REQUEST` SMALLINT UNSIGNED NOT NULL,
  `REASON` VARCHAR(255) NOT NULL,
   UNIQUE (`IP_ADDRESS`),
   PRIMARY KEY (`ID`),
   CONSTRAINT `FK_IP_ADDRESS` FOREIGN KEY (`IP_ADDRESS`) REFERENCES `PARSER`.`LOG_ENTRIES`(`IP_ADDRESS`)
);
