-- Write MySQL query to find IPs that mode more than a certain number of requests for a given time period.

SELECT INET_NTOA(IP_ADDRESS) IP, REQUEST_DATE, COUNT(IP_ADDRESS) IP_COUNT 
FROM PARSER.LOG_ENTRIES
WHERE REQUEST_DATE  BETWEEN "2017-01-01.00:00:00" AND "2017-01-02.00:00:00"
GROUP BY IP_ADDRESS 
HAVING IP_COUNT >= 500;

-- Write MySQL query to find requests made by a given IP.
SELECT REQUEST_DATE, INET_NTOA(IP_ADDRESS) IP, REQUEST_METHOD, STATUS, USER_AGENT
FROM PARSER.LOG_ENTRIES 
WHERE INET_NTOA(IP_ADDRESS) = "192.168.199.209";