DROP SCHEMA IF EXISTS PARSER;

CREATE SCHEMA IF NOT EXISTS PARSER;

CREATE TABLE IF NOT EXISTS `PARSER`.`LOG_ENTRIES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `REQUEST_DATE` TIMESTAMP(3) NOT NULL,
  `IP_ADDRESS` VARCHAR(20) NOT NULL,
  `REQUEST_METHOD` VARCHAR(20) NOT NULL,
  `STATUS` SMALLINT NOT NULL,
  `USER_AGENT` VARCHAR(255) NOT NULL,
  UNIQUE (`REQUEST_DATE`, `IP_ADDRESS`),
  PRIMARY KEY (`ID`),
  INDEX `IP_ADDRESS` (`IP_ADDRESS` ASC)
);

CREATE TABLE IF NOT EXISTS `PARSER`.`BLOCK_REASON` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `START_DATE` TIMESTAMP NOT NULL,
  `DURATION` VARCHAR(10) NOT NULL,
  `THRESHOLD` INT NOT NULL,
   UNIQUE (`START_DATE`, `DURATION`, `THRESHOLD`),
   PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `PARSER`.`BLOCKED_IPS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `IP_ADDRESS` VARCHAR(20) UNSIGNED NOT NULL,
  `NUM_REQUEST` SMALLINT UNSIGNED NOT NULL,
  `REASON` INT NOT NULL,
   PRIMARY KEY (`ID`),
   UNIQUE (`IP_ADDRESS`, `REASON`),
   CONSTRAINT `FK_IP_ADDRESS` FOREIGN KEY (`IP_ADDRESS`) REFERENCES `PARSER`.`LOG_ENTRIES`(`IP_ADDRESS`),
   CONSTRAINT `FK_BLOCK_REASON` FOREIGN KEY (`REASON`) REFERENCES `PARSER`.`BLOCK_REASON`(`ID`)
);


